# Generated by Django 5.2.14 on 2026-05-31 11:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_interviews", "0005_remove_userinterviewtopic_interviewee_cohort_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinterview",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("abandoned", "Abandoned"),
                        ("short", "Short"),
                        ("off-topic", "Off-topic"),
                        ("long", "Long"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
