# Generated by Django 5.2.14 on 2026-05-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1186_activitylog_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
